# Schools in New York drinking water safe and does not have lead 
In this notebook I first read in the data, dropped columns that did not have testable data in them, then split the data into Training and testing sets to check the accuracy of the following question:
    Are there any schools in New york that have Lead Free Plumbing? 

In [10]:
# Dependencies
import numpy as np
import pandas as pd
import datetime as dt
import requests
import json
from pprint import pprint
from matplotlib import style
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler

In [11]:
#  Import and read the combined csv
df=pd.read_csv(Path('../brittany_analysis/data/cleaned_water_data.csv'))
df.tail()

County    Zip              School Type of Organization  \
3361  Wyoming  14427       LETCHWORTH HS        Public School   
3362  Wyoming  14427       LETCHWORTH MS        Public School   
3363  Wyoming  14569  WARSAW ELEM SCHOOL        Public School   
3364  Wyoming  14569      WARSAW J S H S        Public School   
3365    Yates  14527    PENN YAN ACADEMY        Public School   

     Any Building with Lead-Free Plumbing?  \
3361                                    No   
3362                                    No   
3363                                    No   
3364                                    No   
3365                 Yes (Entire Building)   

      Number of Outlets that Require Sampling  Outlets ≤ 15 ppb  \
3361                                     49.0              42.0   
3362                                     35.0              28.0   
3363                                     52.0              51.0   
3364                                     47.0              44.0   
3365                                     44.0              43.0   

      Outlets > 15 ppb          County Location  
3361               7.0  (42.723641, -78.204473)  
3362               7.0  (42.723641, -78.204473)  
3363               1.0  (42.723641, -78.204473)  
3364               3.0  (42.723641, -78.204473)  
3365               1.0  (42.634338, -77.078311)

In [12]:
#Drop specific columns that are not needed 
df=df.drop(columns=['County','County Location','Type of Organization','School'])


In [13]:
#Select your features (columns)
df.columns

Index(['Zip', 'Any Building with Lead-Free Plumbing?',
       'Number of Outlets that Require Sampling', 'Outlets ≤ 15 ppb',
       'Outlets > 15 ppb'],
      dtype='object')

In [14]:
df

Zip Any Building with Lead-Free Plumbing?  \
0     12009                                    No   
1     12047                                    No   
2     12047                                    No   
3     12047                                    No   
4     12047                                    No   
...     ...                                   ...   
3361  14427                                    No   
3362  14427                                    No   
3363  14569                                    No   
3364  14569                                    No   
3365  14527                 Yes (Entire Building)   

      Number of Outlets that Require Sampling  Outlets ≤ 15 ppb  \
0                                        63.0              63.0   
1                                        74.0              74.0   
2                                        81.0              80.0   
3                                        53.0              53.0   
4                                        86.0              86.0   
...                                       ...               ...   
3361                                     49.0              42.0   
3362                                     35.0              28.0   
3363                                     52.0              51.0   
3364                                     47.0              44.0   
3365                                     44.0              43.0   

      Outlets > 15 ppb  
0                  0.0  
1                  0.0  
2                  1.0  
3                  0.0  
4                  0.0  
...                ...  
3361               7.0  
3362               7.0  
3363               1.0  
3364               3.0  
3365               1.0  

[3366 rows x 5 columns]

# Split the Data into Training and Testing Sets
Use 'Any Building with Lead-Free Plumbing' for the y value to determine if there are any school building in the New York area with lead free plumbing.

In [15]:
#Set features that will be used as our y and x values
y=df['Any Building with Lead-Free Plumbing?']
X=df.drop(columns='Any Building with Lead-Free Plumbing?')

In [16]:
#Review the y variable 
y[:5]

0    No
1    No
2    No
3    No
4    No
Name: Any Building with Lead-Free Plumbing?, dtype: object

In [17]:
y.value_counts()

No                        3297
Yes (Entire Building)       31
Yes (Partial Building)      22
Yes                         16
Name: Any Building with Lead-Free Plumbing?, dtype: int64

In [18]:
#Review the X variable 
X[:5]

Zip  Number of Outlets that Require Sampling  Outlets ≤ 15 ppb  \
0  12009                                     63.0              63.0   
1  12047                                     74.0              74.0   
2  12047                                     81.0              80.0   
3  12047                                     53.0              53.0   
4  12047                                     86.0              86.0   

   Outlets > 15 ppb  
0               0.0  
1               0.0  
2               1.0  
3               0.0  
4               0.0

In [19]:
#Check the balance of the targeted value 
y.value_counts()

No                        3297
Yes (Entire Building)       31
Yes (Partial Building)      22
Yes                         16
Name: Any Building with Lead-Free Plumbing?, dtype: int64

In [20]:
#create a Train Test Split 
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

## Logistical Regression Model

In [21]:
#Create a Logistic Regression Model by using the training data 
lr_model=LogisticRegression(random_state=42)
#Fit the model using the training Data 
training_model=lr_model.fit(X_train,y_train)

c:\Users\britt\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
#make a prediction using testing data 
testing_predictions=training_model.predict(X_test)

In [23]:
#Show the balanced accuracy score of the model
balanced_model=balanced_accuracy_score(y_test, testing_predictions) 
print(balanced_model)

0.24969843184559712


In [24]:
# Generate a confusion matrix for the model
matrix_model=confusion_matrix(y_test,testing_predictions)
print(matrix_model)

[[828   1   0   0]
 [  3   0   0   0]
 [  9   0   0   0]
 [  1   0   0   0]]


In [25]:
# Print the classification report for the model
classification_model=classification_report(y_test,testing_predictions)
print(classification_model)

c:\Users\britt\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                        precision    recall  f1-score   support

                    No       0.98      1.00      0.99       829
                   Yes       0.00      0.00      0.00         3
 Yes (Entire Building)       0.00      0.00      0.00         9
Yes (Partial Building)       0.00      0.00      0.00         1

              accuracy                           0.98       842
             macro avg       0.25      0.25      0.25       842
          weighted avg       0.97      0.98      0.98       842



c:\Users\britt\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\britt\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Predicting a Logistical Regression Model with Resampled Training Data 
using RandomOverSampler

In [26]:
# RandomOverSampler to resample the data 
# # Assign a random_state parameter of 42
random_oversampler_model=RandomOverSampler(random_state=42)

# Fit the original training data to the random_oversampler model
X_oversample, y_oversample = random_oversampler_model.fit_resample(X_train,y_train)

In [27]:
# Count the distinct values of the resampled labels data
y_oversample.value_counts()

No                        2468
Yes                       2468
Yes (Partial Building)    2468
Yes (Entire Building)     2468
Name: Any Building with Lead-Free Plumbing?, dtype: int64

In [28]:
#Logistic Regression Model
random_state_model=LogisticRegression(solver='lbfgs', random_state=42)

# Fit the model using the resampled training data
random_state_model.fit(X_oversample,y_oversample)

# Make a prediction using the testing data
y_prediction=random_state_model.predict(X_test)

c:\Users\britt\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [29]:
# Print the balanced_accuracy score of the model 
balanced_accuracy_score(y_test, y_prediction)

0.37943975338426483

In [30]:
# Generate a confusion matrix for the model
print(confusion_matrix(y_test, y_prediction))

[[245 166 321  97]
 [  1   2   0   0]
 [  1   1   5   2]
 [  1   0   0   0]]


In [31]:
# Print the classification report for the model
print(classification_report(y_test, y_prediction))

                        precision    recall  f1-score   support

                    No       0.99      0.30      0.45       829
                   Yes       0.01      0.67      0.02         3
 Yes (Entire Building)       0.02      0.56      0.03         9
Yes (Partial Building)       0.00      0.00      0.00         1

              accuracy                           0.30       842
             macro avg       0.25      0.38      0.13       842
          weighted avg       0.97      0.30      0.45       842

